import { TrendingUp, TrendingDown, Minus, Loader2 } from "lucide-react";

export const CART_KEY = "portfolioCart_v1";
export const CACHE_KEY = "financialNews_general_cache_v2";
export const PORTFOLIO_CACHE_KEY = "financialNews_portfolio_cache_v2";
export const CACHE_TTL_MS = 3 * 60 * 60 * 1000;

export const NSE_ALIAS_MAP: Record<string, string> = {
  // Banking
  SBI: "SBIN",
  "STATE BANK": "SBIN",
  "STATE BANK OF INDIA": "SBIN",
  HDFC: "HDFCBANK",
  "HDFC BANK": "HDFCBANK",
  ICICI: "ICICIBANK",
  "ICICI BANK": "ICICIBANK",
  AXIS: "AXISBANK",
  "AXIS BANK": "AXISBANK",
  KOTAK: "KOTAKBANK",
  "KOTAK BANK": "KOTAKBANK",
  "KOTAK MAHINDRA": "KOTAKBANK",
  PNB: "PNB",
  BOB: "BANKBARODA",
  "BANK OF BARODA": "BANKBARODA",
  CANARA: "CANARABANK",
  "CANARA BANK": "CANARABANK",
  INDUSIND: "INDUSINDBK",
  "INDUSIND BANK": "INDUSINDBK",
  YES: "YESBANK",
  "YES BANK": "YESBANK",
  BANDHAN: "BANDHANBNK",
  "BANDHAN BANK": "BANDHANBNK",
  FEDERAL: "FEDERALBNK",
  "FEDERAL BANK": "FEDERALBNK",
  IDFCFIRST: "IDFCFIRSTB",
  "IDFC FIRST": "IDFCFIRSTB",
  "IDFC FIRST BANK": "IDFCFIRSTB",
  RBL: "RBLBANK",
  "RBL BANK": "RBLBANK",
  // FMCG
  NESTLE: "NESTLEINDIA",
  "NESTLE INDIA": "NESTLEINDIA",
  HUL: "HINDUNILVR",
  "HINDUSTAN UNILEVER": "HINDUNILVR",
  "HINDUSTAN LEVER": "HINDUNILVR",
  ITC: "ITC",
  DABUR: "DABUR",
  MARICO: "MARICO",
  GODREJ: "GODREJCP",
  "GODREJ CONSUMER": "GODREJCP",
  "GODREJ INDUSTRIES": "GODREJIND",
  BRITANNIA: "BRITANNIA",
  COLGATE: "COLPAL",
  "COLGATE PALMOLIVE": "COLPAL",
  "PROCTER GAMBLE": "PGHH",
  "P&G": "PGHH",
  EMAMI: "EMAMILTD",
  VARUN: "VBL",
  "VARUN BEVERAGES": "VBL",
  // IT / Tech
  TCS: "TCS",
  INFOSYS: "INFY",
  INFY: "INFY",
  WIPRO: "WIPRO",
  HCLTECH: "HCLTECH",
  "HCL TECH": "HCLTECH",
  "HCL TECHNOLOGIES": "HCLTECH",
  TECHM: "TECHM",
  "TECH MAHINDRA": "TECHM",
  MPHASIS: "MPHASIS",
  LTIMINDTREE: "LTIM",
  "LTI MINDTREE": "LTIM",
  "L&T INFOTECH": "LTIM",
  PERSISTENT: "PERSISTENT",
  COFORGE: "COFORGE",
  OFSS: "OFSS",
  "ORACLE FINANCIAL": "OFSS",
  HEXAWARE: "HEXAWARE",
  CYIENT: "CYIENT",
  // Auto
  MARUTI: "MARUTI",
  "MARUTI SUZUKI": "MARUTI",
  TATA: "TATAMOTORS",
  "TATA MOTORS": "TATAMOTORS",
  MAHINDRA: "M&M",
  "M&M": "M&M",
  "MAHINDRA & MAHINDRA": "M&M",
  "MAHINDRA AND MAHINDRA": "M&M",
  BAJAJ: "BAJAJ-AUTO",
  "BAJAJ AUTO": "BAJAJ-AUTO",
  HERO: "HEROMOTOCO",
  "HERO MOTOCORP": "HEROMOTOCO",
  "HERO HONDA": "HEROMOTOCO",
  EICHER: "EICHERMOT",
  "EICHER MOTORS": "EICHERMOT",
  "ROYAL ENFIELD": "EICHERMOT",
  ASHOK: "ASHOKLEY",
  "ASHOK LEYLAND": "ASHOKLEY",
  TVS: "TVSMOTOR",
  "TVS MOTOR": "TVSMOTOR",
  BOSCH: "BOSCHLTD",
  // Oil & Gas / Energy
  RELIANCE: "RELIANCE",
  RIL: "RELIANCE",
  ONGC: "ONGC",
  "OIL AND NATURAL GAS": "ONGC",
  IOC: "IOC",
  "INDIAN OIL": "IOC",
  BPCL: "BPCL",
  "BHARAT PETROLEUM": "BPCL",
  HPCL: "HPCL",
  "HINDUSTAN PETROLEUM": "HPCL",
  "TATA POWER": "TATAPOWER",
  NTPC: "NTPC",
  POWERGRID: "POWERGRID",
  "POWER GRID": "POWERGRID",
  ADANI: "ADANIENT",
  "ADANI ENT": "ADANIENT",
  "ADANI ENTERPRISES": "ADANIENT",
  "ADANI PORTS": "ADANIPORTS",
  "ADANI GREEN": "ADANIGREEN",
  "ADANI POWER": "ADANIPOWER",
  "ADANI TOTAL GAS": "ATGL",
  "ADANI WILMAR": "AWL",
  GAIL: "GAIL",
  // Pharma
  "SUN PHARMA": "SUNPHARMA",
  SUNPHARMA: "SUNPHARMA",
  "DR REDDY": "DRREDDY",
  "DR. REDDY": "DRREDDY",
  "DR REDDYS": "DRREDDY",
  CIPLA: "CIPLA",
  DIVI: "DIVISLAB",
  "DIVI LAB": "DIVISLAB",
  "DIVI LABORATORIES": "DIVISLAB",
  BIOCON: "BIOCON",
  LUPIN: "LUPIN",
  TORRENT: "TORNTPHARM",
  "TORRENT PHARMA": "TORNTPHARM",
  AUROBINDO: "AUROPHARMA",
  ZYDUS: "ZYDUSLIFE",
  "ZYDUS LIFESCIENCES": "ZYDUSLIFE",
  Abbott: "ABBOTINDIA",
  ALKEM: "ALKEM",
  // Finance / NBFC
  BAJAJFIN: "BAJFINANCE",
  "BAJAJ FINANCE": "BAJFINANCE",
  "BAJAJ FINSERV": "BAJAJFINSV",
  BAJAJFINSV: "BAJAJFINSV",
  "MUTHOOT FINANCE": "MUTHOOTFIN",
  MUTHOOT: "MUTHOOTFIN",
  CHOLAFIN: "CHOLAFIN",
  "CHOLAMANDALAM FINANCE": "CHOLAFIN",
  SHRIRAM: "SHRIRAMFIN",
  "SHRIRAM FINANCE": "SHRIRAMFIN",
  LIC: "LICI",
  "LIC INDIA": "LICI",
  "HDFC LIFE": "HDFCLIFE",
  "SBI LIFE": "SBILIFE",
  "ICICI PRUDENTIAL": "ICICIPRULI",
  "MAX FINANCIAL": "MFSL",
  // Metals / Mining
  TATASTEEL: "TATASTEEL",
  "TATA STEEL": "TATASTEEL",
  JSWSTEEL: "JSWSTEEL",
  "JSW STEEL": "JSWSTEEL",
  HINDALCO: "HINDALCO",
  VEDANTA: "VEDL",
  SAIL: "SAIL",
  NMDC: "NMDC",
  "NATIONAL MINERAL": "NMDC",
  WELSPUN: "WELSPUNIND",
  APL: "APLAPOLLO",
  "APL APOLLO": "APLAPOLLO",
  // Cement
  ULTRATECH: "ULTRACEMCO",
  "ULTRATECH CEMENT": "ULTRACEMCO",
  AMBUJA: "AMBUJACEM",
  "AMBUJA CEMENT": "AMBUJACEM",
  "ACC CEMENT": "ACC",
  ACC: "ACC",
  SHREECEM: "SHREECEM",
  "SHREE CEMENT": "SHREECEM",
  JKCEMENT: "JKCEMENT",
  "JK CEMENT": "JKCEMENT",
  // Telecom
  AIRTEL: "BHARTIARTL",
  "BHARTI AIRTEL": "BHARTIARTL",
  JIO: "RELIANCE",
  "VODAFONE IDEA": "IDEA",
  IDEA: "IDEA",
  // Infra / Real Estate
  "L&T": "LT",
  "LARSEN & TOUBRO": "LT",
  "LARSEN AND TOUBRO": "LT",
  LT: "LT",
  DLF: "DLF",
  GODREJPROP: "GODREJPROP",
  "GODREJ PROPERTIES": "GODREJPROP",
  PRESTIGE: "PRESTIGE",
  SOBHA: "SOBHA",
  "BRIGADE GROUP": "BRIGADE",
  BRIGADE: "BRIGADE",
  // Consumer / Retail
  TITAN: "TITAN",
  TRENT: "TRENT",
  NYKAA: "FSN",
  "NYKAA FSN": "FSN",
  ZOMATO: "ETERNAL",
  SWIGGY: "SWIGGY",
  PAYTM: "PAYTM",
  "ONE 97": "PAYTM",
  POLICYBAZAAR: "POLICYBZR",
  DMART: "DMART",
  "AVENUE SUPERMARTS": "DMART",
  TATACONSUM: "TATACONSUM",
  "TATA CONSUMER": "TATACONSUM",
  // Others
  ASIAN: "ASIANPAINT",
  "ASIAN PAINTS": "ASIANPAINT",
  PIDILITE: "PIDILITIND",
  SIEMENS: "SIEMENS",
  ABB: "ABB",
  HAVELLS: "HAVELLS",
  VOLTAS: "VOLTAS",
  CROMPTON: "CROMPTON",
  BLUEDART: "BLUEDART",
  CONCOR: "CONCOR",
  "CONTAINER CORP": "CONCOR",
  IRCTC: "IRCTC",
  "INDIAN RAILWAY": "IRCTC",
  ZEEL: "ZEEL",
  "ZEE ENT": "ZEEL",
  "ZEE ENTERTAINMENT": "ZEEL",
  SUNTV: "SUNTV",
  "SUN TV": "SUNTV",
  INDIGO: "INDIGO",
  "INTERGLOBE AVIATION": "INDIGO",
  SPICEJET: "SPICEJET",
  MCDOWELL: "MCDOWELL-N",
  "UNITED SPIRITS": "MCDOWELL-N",
  UBL: "UBL",
  "UNITED BREWERIES": "UBL",
  PAGEIND: "PAGEIND",
  "PAGE INDUSTRIES": "PAGEIND",
  DIXON: "DIXON",
  AMBER: "AMBER",
  KAYNES: "KAYNES",
  JYOTHY: "JYOTHYLAB",
  "JYOTHY LABS": "JYOTHYLAB",
};

export function normalizeNseTicker(raw: string): string {
  const upper = raw.trim().toUpperCase();
  if (NSE_ALIAS_MAP[upper]) return NSE_ALIAS_MAP[upper];
  for (const [alias, canonical] of Object.entries(NSE_ALIAS_MAP)) {
    if (upper === alias.toUpperCase()) return canonical;
  }
  return upper;
}

export const GENERAL_NEWSDATA_QUERIES = [
  { q: "Sensex Nifty India", category: "business" },
  { q: "NSE BSE stock market India", category: "business" },
  { q: "India economy RBI rate", category: "business" },
  { q: "India IPO listing 2025", category: "business" },
  { q: "India earnings quarterly results profit", category: "business" },
  { q: "India startup funding raise", category: "business" },
  { q: "FII FPI India investment", category: "business" },
  { q: "India GDP growth exports", category: "business" },
  { q: "Reliance TCS Infosys results", category: "business" },
  { q: "India banking HDFC ICICI SBI", category: "business" },
  { q: "India pharma auto sector stock", category: "business" },
  { q: "Adani Tata Mahindra shares", category: "business" },
  { q: "India crude oil commodity market", category: "business" },
  { q: "SEBI regulation India market", category: "business" },
  { q: "India mutual fund SIP investment", category: "business" },
  { q: "NSE BSE midcap smallcap India", category: "business" },
];

export const GENERAL_GNEWS_QUERIES = [
  "Sensex Nifty stock India",
  "India IPO shares listing",
  "India company earnings results",
  "Indian economy investment",
  "India stock market today",
  "BSE NSE trading session India",
  "India IT sector stocks",
  "India banking finance stocks",
];

export const RSS_FEEDS = [
  {
    url: "https://economictimes.indiatimes.com/markets/rssfeeds/1977021573.cms",
    label: "ET Markets",
  },
  {
    url: "https://economictimes.indiatimes.com/markets/stocks/rssfeeds/2146842.cms",
    label: "ET Stocks",
  },
  { url: "https://www.livemint.com/rss/markets", label: "Livemint" },
  {
    url: "https://economictimes.indiatimes.com/industry/rssfeeds/13358374.cms",
    label: "ET Industry",
  },
  {
    url: "https://economictimes.indiatimes.com/wealth/rssfeeds/837555174.cms",
    label: "ET Wealth",
  },
];

export const S = {
  positive: {
    label: "Bullish",
    Icon: TrendingUp,
    color: "var(--green)",
    dot: "var(--green)",
  },
  negative: {
    label: "Bearish",
    Icon: TrendingDown,
    color: "var(--red)",
    dot: "var(--red)",
  },
  neutral: { label: "Neutral", Icon: Minus, color: "var(--amber)", dot: "var(--amber)" },
  pending: {
    label: "Analyzing",
    Icon: Loader2,
    color: "hsl(var(--muted-foreground))",
    dot: "hsl(var(--muted-foreground))",
  },
};

export const TREND_CONFIG = {
  strong_buy: {
    label: "Strong Buy",
    color: "var(--green)",
    bg: "var(--green-subtle)",
    border: "var(--green-border)",
  },
  buy: {
    label: "Buy",
    color: "var(--green)",
    bg: "var(--green-subtle)",
    border: "var(--green-border)",
  },
  hold: {
    label: "Hold",
    color: "var(--amber)",
    bg: "var(--amber-subtle)",
    border: "var(--amber-border)",
  },
  sell: {
    label: "Sell",
    color: "var(--red)",
    bg: "var(--red-subtle)",
    border: "var(--red-border)",
  },
  strong_sell: {
    label: "Strong Sell",
    color: "var(--red)",
    bg: "var(--red-subtle)",
    border: "var(--red-border)",
  },
};

export const CONFIDENCE_CONFIG = {
  low: { label: "Low data", color: "hsl(var(--muted-foreground))", icon: "◌" },
  medium: { label: "Medium data", color: "var(--amber)", icon: "◑" },
  high: { label: "High data", color: "var(--green)", icon: "●" },
};

export const BATCH = 12;

export const toTitleCase = (s: string) =>
  s.replace(
    /\w\S*/g,
    (w) => w.charAt(0).toUpperCase() + w.slice(1).toLowerCase(),
  );

export const Z = {
  articleBackdrop: 50,
  articlePanel: 51,
  signalBackdrop: 52,
  signalPanel: 53,
  nestedArticleBackdrop: 54,
  nestedArticlePanel: 55,
  cartToast: 60,
};
